### ISSUE TITLE
Could not generate pulse using the Phaser code

### ISSUE THREAD

**Issue by Yueh-H** [quartiq/phaser#22]
I tried to generate a signal from Phaser using the following code, 
https://github.com/quartiq/phaser/blob/master/example.py

my device_db.py file is following
`
device_db["phaser0"] = {
"type": "local",
"module": "artiq.coredevice.phaser",
"class": "Phaser",
"arguments": {
"channel_base": 0x010000,
"miso_delay": 1,
}
}
`
but it only generates one pulse noisy, and something prints then there is no  continuous signal?
![image](https://github.com/quartiq/phaser/assets/62708281/f9285a86-54d5-4e55-92bc-bc3d2042a819)

![AWG_pulseNoisy](https://github.com/quartiq/phaser/assets/62708281/454e786f-c2a1-42d3-89f1-c9492dfc5db0)

Did I miss something? Thank you

I just get the noisy pulse

**Comment by jordens** [comment]
* please use the support contact with your supplier or the forum for support requests like these.
* please verify proper hardware and software setup with artiq_sinara_tester. if that works, the issue is likely with your code.
* you may want to check with a spectrum analyzer instead of an oscilloscope
